// Dữ liệu thời khóa biểu từ Excel
const scheduleData = {
    school: "Trường THCS Yên Phúc",
    semester: 1,
    academicYear: "2026-2027",
    appliedFrom: "14/09/2026",
    classes: ["6A01", "6A02", "6A03", "7A01", "7A02", "7A03", "8A01", "8A02", "8A03", "9A01", "9A02", "9A03", "9A04"],
    schedule: {
        2: {
            morning: [
                {
                    period: 1,
                    "6A01": "CHÀO CỜ - Huy",
                    "6A02": "CHÀO CỜ - Hạnh",
                    "6A03": "CHÀO CỜ - Huân",
                    "7A01": "CHÀO CỜ - Vân",
                    "7A02": "CHÀO CỜ - Hân",
                    "7A03": "CHÀO CỜ - Thục",
                    "8A01": "CHÀO CỜ - Hà",
                    "8A02": "CHÀO CỜ - Luyên",
                    "8A03": "CHÀO CỜ - Thiều",
                    "9A01": "CHÀO CỜ - Việt",
                    "9A02": "CHÀO CỜ - Nhung",
                    "9A03": "CHÀO CỜ - Định",
                    "9A04": "CHÀO CỜ - Quỳnh"
                },
                {
                    period: 2,
                    "6A01": "VAN - Tâm",
                    "6A02": "VAN - Năm",
                    "6A03": "TD - Luyên",
                    "7A01": "DIA - Hiệp",
                    "7A02": "CN - Thúy",
                    "7A03": "TOAN - Thanh",
                    "8A01": "KHTN ( L) - Hân",
                    "8A02": "VAN - Bài",
                    "8A03": "VAN - Thiều",
                    "9A01": "KHTN (S) - Nhung",
                    "9A02": "VAN - Thục",
                    "9A03": "TOAN - Kỳ",
                    "9A04": "CN - Trang"
                },
                {
                    period: 3,
                    "6A01": "KHTN (H) - Ban",
                    "6A02": "MT - Huy",
                    "6A03": "VAN - Tâm",
                    "7A01": "TOAN - Thanh",
                    "7A02": "TIN - Việt",
                    "7A03": "SU - H - Tuấn",
                    "8A01": "TOAN - Kỳ",
                    "8A02": "GDCD - Hà",
                    "8A03": "VAN - Thiều",
                    "9A01": "VAN - Năm",
                    "9A02": "TOAN - Hân",
                    "9A03": "GDDP - Bài",
                    "9A04": "TIẾNG ANH - Định"
                },
                {
                    period: 4,
                    "6A01": "TIẾNG ANH - H- Huyền",
                    "6A02": "KHTN (H) - Ban",
                    "6A03": "KHTN ( L) - Thúy",
                    "7A01": "SU - H - Tuấn",
                    "7A02": "TOAN - Hân",
                    "7A03": "VAN - Thục",
                    "8A01": "CN - Trang",
                    "8A02": "TOAN - Kỳ",
                    "8A03": "DIA - Hiệp",
                    "9A01": "TOAN - Nguyệt",
                    "9A02": "TIẾNG ANH - Hạnh",
                    "9A03": "GDCD - Huy",
                    "9A04": "TOAN - Thanh"
                },
                {
                    period: 5,
                    "6A01": "CN - Trang",
                    "6A02": "SU - H - Tuấn",
                    "6A03": "TIẾNG ANH - H- Huyền",
                    "7A01": "KHTN (S) - Nhung",
                    "7A02": "KHTN (H) - Ban",
                    "7A03": "CN - Thúy",
                    "8A01": "DIA - Tâm",
                    "8A02": "TIN - Nguyệt",
                    "8A03": "TOAN - Hòa",
                    "9A01": "GDCD - Hà",
                    "9A02": "GDDP - Bài",
                    "9A03": "DIA - Hiệp",
                    "9A04": "KHTN ( L) - Kỳ"
                }
            ],
            afternoon: [
                {
                    period: 1,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 2,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 3,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 4,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                }
            ]
        },
        3: {
            morning: [
                {
                    period: 1,
                    "6A01": "KHTN (S) - Ban",
                    "6A02": "TOAN - Thúy",
                    "6A03": "TIẾNG ANH - H- Huyền",
                    "7A01": "VAN - Huân",
                    "7A02": "TIẾNG ANH - Bình",
                    "7A03": "VAN - Thục",
                    "8A01": "TOAN - Kỳ",
                    "8A02": "DIA - Hiệp",
                    "8A03": "VAN - Thiều",
                    "9A01": "TD - Mạnh",
                    "9A02": "GDCD - Hà",
                    "9A03": "TIN - Việt",
                    "9A04": "TIẾNG ANH - Định"
                },
                {
                    period: 2,
                    "6A01": "VAN - Tâm",
                    "6A02": "KHTN (S) - Ban",
                    "6A03": "TD - Luyên",
                    "7A01": "TIN - Việt",
                    "7A02": "TIẾNG ANH - Bình",
                    "7A03": "TIẾNG ANH - Hạnh",
                    "8A01": "VAN - Tuyến",
                    "8A02": "TOAN - Kỳ",
                    "8A03": "TOAN - Hòa",
                    "9A01": "TIẾNG ANH - H- Huyền",
                    "9A02": "KHTN (S) - Nhung",
                    "9A03": "VAN - Thiều",
                    "9A04": "TOAN - Thanh"
                },
                {
                    period: 3,
                    "6A01": "VAN - Tâm",
                    "6A02": "KHTN ( L) - Thúy",
                    "6A03": "DIA - Hiệp",
                    "7A01": "TD - Vân",
                    "7A02": "VAN - Bài",
                    "7A03": "TOAN - Thanh",
                    "8A01": "VAN - Tuyến",
                    "8A02": "KHTN (H) - Ban",
                    "8A03": "TD - Mạnh",
                    "9A01": "CN - Trang",
                    "9A02": "VAN - Thục",
                    "9A03": "TOAN - Kỳ",
                    "9A04": "SU - Năm"
                },
                {
                    period: 4,
                    "6A01": "TIN - Việt",
                    "6A02": "VAN - Năm",
                    "6A03": "CN - Thúy",
                    "7A01": "TOAN - Thanh",
                    "7A02": "TOAN - Hân",
                    "7A03": "DIA - Hiệp",
                    "8A01": "CN - Trang",
                    "8A02": "VAN - Bài",
                    "8A03": "TIẾNG ANH - Bình",
                    "9A01": "MT - Huy",
                    "9A02": "TD - Mạnh",
                    "9A03": "KHTN (H) - Lý",
                    "9A04": "VAN - Huân"
                },
                {
                    period: 5,
                    "6A01": "GDDP - Bài",
                    "6A02": "DIA - Tâm",
                    "6A03": "",
                    "7A01": "DIA - Hiệp",
                    "7A02": "MT - Huy",
                    "7A03": "GDDP - Thiều",
                    "8A01": "TIẾNG ANH - Định",
                    "8A02": "KHTN ( L) - Hân",
                    "8A03": "SU - H - Tuấn",
                    "9A01": "",
                    "9A02": "NHAC - Quỳnh",
                    "9A03": "SU - Năm",
                    "9A04": "MT - Hà"
                }
            ],
            afternoon: [
                {
                    period: 1,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "NHAC - Quỳnh",
                    "9A02": "TrNg - Bài",
                    "9A03": "TIẾNG ANH - Định",
                    "9A04": "CN - Trang"
                },
                {
                    period: 2,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "SU - H - Tuấn",
                    "9A02": "TrNg - Bài",
                    "9A03": "NHAC - Quỳnh",
                    "9A04": "TIN - Việt"
                },
                {
                    period: 3,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "TIN - Việt",
                    "9A02": "TrNg - Bài",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 4,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                }
            ]
        },
        4: {
            morning: [
                {
                    period: 1,
                    "6A01": "KHTN (S) - Ban",
                    "6A02": "TIẾNG ANH - Hạnh",
                    "6A03": "CN - Thúy",
                    "7A01": "NHAC - Chuyên",
                    "7A02": "KHTN (S) - Nhung",
                    "7A03": "KHTN ( L) - H-Hạnh",
                    "8A01": "TOAN - Kỳ",
                    "8A02": "MT - Hà",
                    "8A03": "TOAN - Hòa",
                    "9A01": "TIẾNG ANH - H- Huyền",
                    "9A02": "TOAN - Hân",
                    "9A03": "TD - Vân",
                    "9A04": "VAN - Huân"
                },
                {
                    period: 2,
                    "6A01": "TIẾNG ANH - H- Huyền",
                    "6A02": "TOAN - Thúy",
                    "6A03": "VAN - Tâm",
                    "7A01": "KHTN ( L) - H-Hạnh",
                    "7A02": "NHAC - Chuyên",
                    "7A03": "TIN - Việt",
                    "8A01": "KHTN (H) - Ban",
                    "8A02": "VAN - Bài",
                    "8A03": "KHTN ( L) - Kỳ",
                    "9A01": "VAN - Năm",
                    "9A02": "CN - Trang",
                    "9A03": "VAN - Thiều",
                    "9A04": "VAN - Huân"
                },
                {
                    period: 3,
                    "6A01": "SU - H - Tuấn",
                    "6A02": "GDCD - Huy",
                    "6A03": "VAN - Tâm",
                    "7A01": "TIẾNG ANH - Hạnh",
                    "7A02": "KHTN ( L) - H-Hạnh",
                    "7A03": "NHAC - Chuyên",
                    "8A01": "TD - Luyên",
                    "8A02": "KHTN ( L) - Hân",
                    "8A03": "MT - Hà",
                    "9A01": "TOAN - Nguyệt",
                    "9A02": "VAN - Thục",
                    "9A03": "VAN - Thiều",
                    "9A04": "TOAN - Thanh"
                },
                {
                    period: 4,
                    "6A01": "CN - Trang",
                    "6A02": "TIẾNG ANH - Hạnh",
                    "6A03": "SU - H - Tuấn",
                    "7A01": "VAN - Huân",
                    "7A02": "TOAN - Hân",
                    "7A03": "TOAN - Thanh",
                    "8A01": "DIA - Tâm",
                    "8A02": "TIẾNG ANH - Định",
                    "8A03": "NHAC - Quỳnh",
                    "9A01": "TOAN - Nguyệt",
                    "9A02": "VAN - Thục",
                    "9A03": "TOAN - Kỳ",
                    "9A04": "DIA - Ơn"
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "TIẾNG ANH - Định",
                    "8A02": "GDDP - H - Tuấn",
                    "8A03": "CN - Trang",
                    "9A01": "GDDP - Bài",
                    "9A02": "",
                    "9A03": "SU - Năm",
                    "9A04": "GDCD - Huy"
                }
            ],
            afternoon: [
                {
                    period: 1,
                    "6A01": "TrNg - Bài",
                    "6A02": "SU - H - Tuấn",
                    "6A03": "TrNg - Huân",
                    "7A01": "CN - Thúy",
                    "7A02": "GDDP - Thiều",
                    "7A03": "TD - Vân",
                    "8A01": "MT - Hà",
                    "8A02": "TD - Luyên",
                    "8A03": "KHTN (H) - Ban",
                    "9A01": "TrNg - Nhương",
                    "9A02": "MT - Huy",
                    "9A03": "TrNg - D- Tuấn",
                    "9A04": "TrNg - Quỳnh"
                },
                {
                    period: 2,
                    "6A01": "TrNg - Bài",
                    "6A02": "TD - Luyên",
                    "6A03": "TrNg - Huân",
                    "7A01": "MT - Huy",
                    "7A02": "SU - Thục",
                    "7A03": "GDCD - Hà",
                    "8A01": "KHTN ( L) - Hân",
                    "8A02": "CN - Trang",
                    "8A03": "KHTN ( L) - Kỳ",
                    "9A01": "TrNg - Nhương",
                    "9A02": "SU - H - Tuấn",
                    "9A03": "TrNg - D- Tuấn",
                    "9A04": "TrNg - Quỳnh"
                },
                {
                    period: 3,
                    "6A01": "TrNg - Bài",
                    "6A02": "TIẾNG ANH - Hạnh",
                    "6A03": "TrNg - Huân",
                    "7A01": "GDDP - Thiều",
                    "7A02": "TD - Vân",
                    "7A03": "KHTN (H) - Ban",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "TrNg - Nhương",
                    "9A02": "KHTN ( L) - Hân",
                    "9A03": "TrNg - D- Tuấn",
                    "9A04": "TrNg - Quỳnh"
                },
                {
                    period: 4,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                }
            ]
        },
        5: {
            morning: [
                {
                    period: 1,
                    "6A01": "TD - Luyên",
                    "6A02": "TOAN - Thúy",
                    "6A03": "NHAC - D- Tuấn",
                    "7A01": "TIẾNG ANH - Hạnh",
                    "7A02": "TIẾNG ANH - Bình",
                    "7A03": "TOAN - Thanh",
                    "8A01": "TOAN - Kỳ",
                    "8A02": "VAN - Bài",
                    "8A03": "DIA - Hiệp",
                    "9A01": "CN - Trang",
                    "9A02": "TOAN - Hân",
                    "9A03": "MT - Huy",
                    "9A04": "SU - Năm"
                },
                {
                    period: 2,
                    "6A01": "KHTN ( L) - Thúy",
                    "6A02": "TIN - Việt",
                    "6A03": "GDCD - Huy",
                    "7A01": "TOAN - Thanh",
                    "7A02": "DIA - Hiệp",
                    "7A03": "KHTN (S) - Nhung",
                    "8A01": "VAN - Tuyến",
                    "8A02": "NHAC - Quỳnh",
                    "8A03": "TD - Mạnh",
                    "9A01": "VAN - Năm",
                    "9A02": "TOAN - Hân",
                    "9A03": "TIẾNG ANH - Định",
                    "9A04": "TD - Vân"
                },
                {
                    period: 3,
                    "6A01": "DIA - Hiệp",
                    "6A02": "CN - Trang",
                    "6A03": "GDDP - Bài",
                    "7A01": "KHTN (S) - Nhung",
                    "7A02": "TOAN - Hân",
                    "7A03": "TD - Vân",
                    "8A01": "VAN - Tuyến",
                    "8A02": "SU - H - Tuấn",
                    "8A03": "TIẾNG ANH - Bình",
                    "9A01": "TOAN - Nguyệt",
                    "9A02": "TD - Mạnh",
                    "9A03": "TOAN - Kỳ",
                    "9A04": "TOAN - Thanh"
                },
                {
                    period: 4,
                    "6A01": "NHAC - D- Tuấn",
                    "6A02": "TD - Luyên",
                    "6A03": "SU - H - Tuấn",
                    "7A01": "KHTN (H) - Ban",
                    "7A02": "VAN - Bài",
                    "7A03": "VAN - Thục",
                    "8A01": "TIẾNG ANH - Định",
                    "8A02": "TOAN - Kỳ",
                    "8A03": "TIẾNG ANH - Bình",
                    "9A01": "TD - Mạnh",
                    "9A02": "TIẾNG ANH - Hạnh",
                    "9A03": "TD - Vân",
                    "9A04": "KHTN (S) - Nhung"
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "KHTN (H) - Ban",
                    "9A02": "DIA - Hiệp",
                    "9A03": "CN - Trang",
                    "9A04": ""
                }
            ],
            afternoon: [
                {
                    period: 1,
                    "6A01": "GDCD - Huy",
                    "6A02": "TrNg - Hạnh",
                    "6A03": "TIẾNG ANH - H- Huyền",
                    "7A01": "TrNg - Vân",
                    "7A02": "TrNg - Thúy",
                    "7A03": "TrNg - Chuyên",
                    "8A01": "TrNg - Hà",
                    "8A02": "TrNg - Luyên",
                    "8A03": "TrNg - Thiều",
                    "9A01": "BD học sinh giỏi LS - ĐL ( Hiệp - Năm)",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 2,
                    "6A01": "MT - Huy",
                    "6A02": "TrNg - Hạnh",
                    "6A03": "KHTN (S) - Ban",
                    "7A01": "TrNg - Vân",
                    "7A02": "TrNg - Thúy",
                    "7A03": "TrNg - Chuyên",
                    "8A01": "TrNg - Hà",
                    "8A02": "TrNg - Luyên",
                    "8A03": "TrNg - Thiều",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 3,
                    "6A01": "TIẾNG ANH - H- Huyền",
                    "6A02": "TrNg - Hạnh",
                    "6A03": "MT - Huy",
                    "7A01": "TrNg - Vân",
                    "7A02": "TrNg - Thúy",
                    "7A03": "TrNg - Chuyên",
                    "8A01": "TrNg - Hà",
                    "8A02": "TrNg - Luyên",
                    "8A03": "TrNg - Thiều",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 4,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                }
            ]
        },
        6: {
            morning: [
                {
                    period: 1,
                    "6A01": "SU - H - Tuấn",
                    "6A02": "VAN - Năm",
                    "6A03": "TOAN - Chi",
                    "7A01": "VAN - Huân",
                    "7A02": "TD - Vân",
                    "7A03": "TIẾNG ANH - Hạnh",
                    "8A01": "NHAC - Quỳnh",
                    "8A02": "TOAN - Kỳ",
                    "8A03": "TOAN - Hòa",
                    "9A01": "DIA - Hiệp",
                    "9A02": "TOAN - Hân",
                    "9A03": "TIẾNG ANH - Định",
                    "9A04": "TOAN - Thanh"
                },
                {
                    period: 2,
                    "6A01": "VAN - Tâm",
                    "6A02": "VAN - Năm",
                    "6A03": "TOAN - Chi",
                    "7A01": "VAN - Huân",
                    "7A02": "VAN - Bài",
                    "7A03": "VAN - Thục",
                    "8A01": "TIN - Nguyệt",
                    "8A02": "TD - Luyên",
                    "8A03": "CN - Trang",
                    "9A01": "TIẾNG ANH - H- Huyền",
                    "9A02": "SU - H - Tuấn",
                    "9A03": "TOAN - Kỳ",
                    "9A04": "KHTN (H) - Liên"
                },
                {
                    period: 3,
                    "6A01": "VAN - Tâm",
                    "6A02": "TOAN - Thúy",
                    "6A03": "KHTN (H) - Ban",
                    "7A01": "TOAN - Thanh",
                    "7A02": "VAN - Bài",
                    "7A03": "DIA - Hiệp",
                    "8A01": "GDCD - Hà",
                    "8A02": "TIẾNG ANH - Định",
                    "8A03": "TIN - Nguyệt",
                    "9A01": "VAN - Năm",
                    "9A02": "TIẾNG ANH - Hạnh",
                    "9A03": "KHTN (S) - Nhung",
                    "9A04": "KHTN (H) - Liên"
                },
                {
                    period: 4,
                    "6A01": "TOAN - Chi",
                    "6A02": "GDDP - Bài",
                    "6A03": "KHTN (S) - Ban",
                    "7A01": "TD - Vân",
                    "7A02": "DIA - Hiệp",
                    "7A03": "TIẾNG ANH - Hạnh",
                    "8A01": "SU - H - Tuấn",
                    "8A02": "CN - Trang",
                    "8A03": "KHTN ( L) - Kỳ",
                    "9A01": "TOAN - Nguyệt",
                    "9A02": "KHTN (H) - Liên",
                    "9A03": "VAN - Thiều",
                    "9A04": "VAN - Huân"
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "TIN - Việt",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "GDDP - H - Tuấn",
                    "8A02": "DIA - Hiệp",
                    "8A03": "GDCD - Hà",
                    "9A01": "KHTN ( L) - Hân",
                    "9A02": "KHTN (H) - Liên",
                    "9A03": "KHTN (H) - Lý",
                    "9A04": "TIẾNG ANH - Định"
                }
            ],
            afternoon: [
                {
                    period: 1,
                    "6A01": "TD - Luyên",
                    "6A02": "KHTN (S) - Ban",
                    "6A03": "VAN - Tâm",
                    "7A01": "GDCD - Hà",
                    "7A02": "KHTN (S) - Nhung",
                    "7A03": "MT - Huy",
                    "8A01": "KHTN ( L) - Hân",
                    "8A02": "TIẾNG ANH - Định",
                    "8A03": "VAN - Thiều",
                    "9A01": "SU - H - Tuấn",
                    "9A02": "CN - Trang",
                    "9A03": "KHTN ( L) - Kỳ",
                    "9A04": "NHAC - Quỳnh"
                },
                {
                    period: 2,
                    "6A01": "TOAN - Chi",
                    "6A02": "NHAC - D- Tuấn",
                    "6A03": "VAN - Tâm",
                    "7A01": "TIẾNG ANH - Hạnh",
                    "7A02": "GDCD - Hà",
                    "7A03": "KHTN (S) - Nhung",
                    "8A01": "TD - Luyên",
                    "8A02": "KHTN ( L) - Hân",
                    "8A03": "GDDP - H - Tuấn",
                    "9A01": "KHTN (H) - Ban",
                    "9A02": "TIN - Việt",
                    "9A03": "CN - Trang",
                    "9A04": "TD - Vân"
                },
                {
                    period: 3,
                    "6A01": "SH - Huy",
                    "6A02": "SH - Hạnh",
                    "6A03": "SH - Huân",
                    "7A01": "SH - Vân",
                    "7A02": "SH - Hân",
                    "7A03": "SH - Thục",
                    "8A01": "SH - Hà",
                    "8A02": "SH - Luyên",
                    "8A03": "SH - Thiều",
                    "9A01": "SH - Việt",
                    "9A02": "SH - Nhung",
                    "9A03": "SH - Định",
                    "9A04": "SH - Quỳnh"
                },
                {
                    period: 4,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                },
                {
                    period: 5,
                    "6A01": "",
                    "6A02": "",
                    "6A03": "",
                    "7A01": "",
                    "7A02": "",
                    "7A03": "",
                    "8A01": "",
                    "8A02": "",
                    "8A03": "",
                    "9A01": "",
                    "9A02": "",
                    "9A03": "",
                    "9A04": ""
                }
            ]
        }
    }
};
